### ISSUE TITLE
Swift file missing

### ISSUE THREAD

**Issue by auguststurm** [stevencurtis/SwiftCoding#1]
In the **SwiftUI : SwiftUIAuthentication** project directory, the ContentView.swift is missing.

**Comment by stevencurtis** [comment]
The App does not use a `ContentView.swift` file. Take a look at the SwiftUIAuthenticationApp.Swift file, it doesn't reference this.

```
@main
struct SwiftUIAuthenticationApp: App {
    var body: some Scene {
        WindowGroup {
            let nm = NetworkManager(session: URLSession.shared)
            let viewModel = LoginViewModel(networkManager: nm)
            LoginView(viewModel: viewModel)
        }
    }
}
```

**Comment by auguststurm** [comment]
Ahhh, thank you for clearing that up for me!
